### ISSUE TITLE
tweak plantuml representation

### ISSUE THREAD

**Issue by VladimirAlexiev** [int-net/EminentToolArchitecture#1]
@joepvgenuchten

https://github.com/int-net/EminentToolArchitecture/blob/ea88311f0658b588af41fcc450d2678f9fde3312/InformationModels/AnswersetProfile.plantuml#L1
- any "title" after the `@startuml` directive is ignored. (This one is also misleading, since further down you see the real `title Responses Profile`)
- Add `hide empty members` to each file (right after `@startuml`), to eliminate the empty compartments in nodes. I hope this will apply directly to this: https://github.com/int-net/EminentResultsDatabase ?

**Comment by joepvgenuchten** [comment]
Hi, thanks for the feedback. I'll get on it. As for the first point. My understanding is that the title after startuml determines the filename and the title in the title section is the one that is displayed in the graph. Us your suggestion to align those or to keep the startuml one empty?

And yes, these diagrams are also used in the eminent results database repo documentation

**Comment by VladimirAlexiev** [comment]
It uses the input file name to determine the output file name: https://plantuml.com/command-line.
You can have several diagrams in one file https://forum.plantuml.net/2203/multiple-diagrams, but I'm not sure how does it determine the output file name in that case: I think it adds a counter.

**Comment by joepvgenuchten** [comment]
![image](https://github.com/int-net/EminentToolArchitecture/assets/35223909/986b29d8-7caf-4279-babc-2ebaed0751ef)

upon some further study:
It uses the name of the file for the output directory  and the name after startuml is used for the filename (in case you have multiple diagrams in the same file, so it is not actually ignored).

When I made this, I wanted to use the file name to align with the profile name that I had in mind (which revolves around the AnswerSet) and wanted to use the title (as displayed in the diagram) to give a less formal/more human readable description of what is being displayed.  

Is there, in your experience/opinion a better naming convention that I could adopt?

**Comment by VladimirAlexiev** [comment]
hi @joepvgenuchten 
I think there's no need for singleton folders that include only one file.
- If you keep multiple diagrams in one puml then use the file name after `@startuml` (but I think, avoid spaces!)
- If you keep single diagrams per puml file, then don't use the file name.

Note: I was about to make an issue for Plantuml when I found the relevant doc https://plantuml.com/sources section "File names". But 
- added some details http://alphadoc.plantuml.com/doc/markdown/en/sources#w5zipec0u9bok362kjmv
- made a link from http://alphadoc.plantuml.com/doc/markdown/en/command-line#sucs2eibgafek362kjbe to that page

**Comment by joepvgenuchten** [comment]
I removed the empty elements, I'm keeping the folders as I foresee that we need different formats (.png vs .svg) for different publications

**Comment by joepvgenuchten** [comment]
I removed the empty elements, I'm keeping the folders as I foresee that we need different formats (.png vs .svg) for different publications
